### PR TITLE
Docker features integration.

### PR DESCRIPTION
**Pull request by deamwork**
**Do NOT merge until all features are ready for use.**

Progress so far:
- [x] Server (b939d9a)
- [x] Web (b939d9a)
- [x]  ~~~Daemon & Agent (Build for binary ONLY*)~~~ 
- [x] Elasticsearch (18ea250)
- [x] MongoDB (18ea250)

Other:
- [x] Docker Compose
- [x] Usage & Document (**~~~test & help wanted~~~ Testing by @Medicean**)

Feel free to comment below.

~~~*Due to daemon & agent features will only build for binary, not dockerlized.~~~ No longer consider for integration due to compatibility issues.

### CODE REVIEW

**Comment by guidao** [comment]
good job 👍

**Comment by deamwork** [comment]
@neargle @ihacku plz mark this pr for "help wanted". thx.

**Comment by Medicean** [comment]
@deamwork I create a PullRequest in your repository to fix some problems and Add the document.  https://github.com/deamwork/yulong-hids/pull/1

**Comment by deamwork** [comment]
@Medicean thx for ur pr and I think it would need a little change. Others are LGTM.

**Pull request merged**
